import { Item, RentalLog } from "@/types/inventory";

export const INITIAL_ITEMS: Item[] = [
  {
    id: "pop-01",
    name: "A2 POP (1F 정문 안내데스크)",
    category: "A2 POP",
    code: "A2-01",
    location: "1F 정문 안내데스크 앞",
    status: "LOANED",
    borrower_name: "이지은 매니저",
    borrower_contact: "홍보마케팅팀",
    loaned_at: "2026-10-05",
    expected_return_date: "2026-10-08",
    returned_at: null,
    description: "주말 사은행사 안내 고지 POP 설치",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "pop-02",
    name: "A2 POP (5F 사운즈 포레스트 입구)",
    category: "A2 POP",
    code: "A2-02",
    location: "5F 사운즈 포레스트 입구",
    status: "AVAILABLE",
    borrower_name: "김민수 대리",
    borrower_contact: "영업기획팀",
    loaned_at: "2026-10-02",
    expected_return_date: "2026-10-04",
    returned_at: "2026-10-04",
    description: "정원 가든 투어 안내 POP",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "pop-03",
    name: "A3 POP (6F 복합문화공간 ALT.1)",
    category: "A3 POP",
    code: "A3-01",
    location: "6F 복합문화공간 ALT.1 티켓부스",
    status: "LOANED",
    borrower_name: "김태호 디렉터",
    borrower_contact: "공간기획실",
    loaned_at: "2026-10-04",
    expected_return_date: "2026-10-07",
    returned_at: null,
    description: "특별 전시 관람 안내 A3 스탠드",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "pop-04",
    name: "A3 POP (B1 대행사장 중앙)",
    category: "A3 POP",
    code: "A3-02",
    location: "B1 대행사장 중앙 기둥 앞",
    status: "AVAILABLE",
    borrower_name: "최유나 파트장",
    borrower_contact: "마케팅실",
    loaned_at: "2026-10-01",
    expected_return_date: "2026-10-03",
    returned_at: "2026-10-03",
    description: "F&B 팝업 안내 A3",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "pop-05",
    name: "철제배너 (B2 지하철 연결통로)",
    category: "철제배너",
    code: "BNR-01",
    location: "B2 지하철 연결통로 입구",
    status: "LOANED",
    borrower_name: "박서준 파트장",
    borrower_contact: "영업기획팀",
    loaned_at: "2026-10-03",
    expected_return_date: "2026-10-09",
    returned_at: null,
    description: "시즌 오프 프로모션 대형 철제 배너",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "pop-06",
    name: "철제배너 (3F 에스컬레이터 상행선)",
    category: "철제배너",
    code: "BNR-02",
    location: "3F 에스컬레이터 상행선 앞",
    status: "AVAILABLE",
    borrower_name: "정하나 매니저",
    borrower_contact: "고객서비스팀",
    loaned_at: "2026-09-28",
    expected_return_date: "2026-10-02",
    returned_at: "2026-10-02",
    description: "멤버십 가입 안내 배너",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_LOGS: RentalLog[] = [
  {
    id: "log-01",
    item_id: "pop-01",
    item_name: "A2 POP (1F 정문 안내데스크)",
    action: "BORROW",
    user_name: "이지은 매니저",
    note: "주말 사은행사 안내 고지",
    timestamp: "2026-10-05T09:00:00Z",
  },
];
