import { Item, RentalLog } from "@/types/inventory";

export const INITIAL_ITEMS: Item[] = [
  {
    id: "pop-01",
    name: "A2 POP (1F 정문 안내데스크)",
    category: "A2 POP",
    code: "A2-01",
    location: "1F 정문 안내데스크 앞",
    status: "LOANED",
    borrower_name: "이지은 매니저",
    borrower_contact: "홍보마케팅팀",
    loaned_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    expected_return_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    description: "주말 사은행사 안내 고지 POP 설치",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "pop-02",
    name: "A2 POP (5F 사운즈 포레스트 입구)",
    category: "A2 POP",
    code: "A2-02",
    location: "5F 사운즈 포레스트 입구",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "보관 중 (상태 양호)",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "pop-03",
    name: "A3 POP (6F 복합문화공간 ALT.1)",
    category: "A3 POP",
    code: "A3-01",
    location: "6F 복합문화공간 ALT.1 티켓부스",
    status: "LOANED",
    borrower_name: "김태호 디렉터",
    borrower_contact: "공간기획실",
    loaned_at: new Date(Date.now() - 3600000 * 6).toISOString(),
    expected_return_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    description: "특별 전시 관람 안내 A3 스탠드",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "pop-04",
    name: "A3 POP (B1 대행사장 중앙)",
    category: "A3 POP",
    code: "A3-02",
    location: "B1 대행사장 중앙 기둥 앞",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "즉시 사용 가능",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "pop-05",
    name: "철제배너 (B2 지하철 연결통로)",
    category: "철제배너",
    code: "BNR-01",
    location: "B2 지하철 연결통로 입구",
    status: "LOANED",
    borrower_name: "박서준 파트장",
    borrower_contact: "영업기획팀",
    loaned_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    expected_return_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    description: "시즌 오프 프로모션 대형 철제 배너",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "pop-06",
    name: "철제배너 (3F 에스컬레이터 상행선)",
    category: "철제배너",
    code: "BNR-02",
    location: "3F 에스컬레이터 상행선 앞",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "양면 거치대 정상 확인",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_LOGS: RentalLog[] = [
  {
    id: "log-01",
    item_id: "pop-01",
    item_name: "A2 POP (1F 정문 안내데스크)",
    action: "BORROW",
    user_name: "이지은 매니저",
    note: "주말 사은행사 안내 고지",
    timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: "log-02",
    item_id: "pop-03",
    item_name: "A3 POP (6F 복합문화공간 ALT.1)",
    action: "BORROW",
    user_name: "김태호 디렉터",
    note: "특별 전시 티켓팅 안내",
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: "log-03",
    item_id: "pop-05",
    item_name: "철제배너 (B2 지하철 연결통로)",
    action: "BORROW",
    user_name: "박서준 파트장",
    note: "지하철 통로 시즌 행사 거치",
    timestamp: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];
