import { Item, RentalLog } from "@/types/inventory";

export const INITIAL_ITEMS: Item[] = [
  {
    id: "hyd-01",
    name: "뱅앤올룹슨 Beosound Explore 포터블 스피커",
    category: "음향/오디오",
    code: "HYD-AU-01",
    location: "6F ALT.1 복합문화공간 라운지",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "아웃도어 방수 블루투스 스피커. 야외 행사 및 라운지 음악 재생용.",
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: "hyd-02",
    name: "라이카 SOFORT 2 하이브리드 즉석 카메라",
    category: "카메라/영상",
    code: "HYD-CAM-02",
    location: "1F 워터폴 가든 안내데스크",
    status: "LOANED",
    borrower_name: "이지은 매니저",
    borrower_contact: "홍보마케팅팀 (내선 2401)",
    loaned_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    expected_return_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    description: "사운즈 포레스트 팝업 스토어 현장 스케치 및 VIP 증정 사진 촬영용.",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: "hyd-03",
    name: "다이슨 에어랩 멀티 스타일러 컴플리트",
    category: "뷰티/스타일링",
    code: "HYD-BT-03",
    location: "5F 사운즈 포레스트 파우더룸",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "임직원 및 쇼룸 촬영용 헤어 스타일링 세트.",
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: "hyd-04",
    name: "맥북 프로 16형 M3 Max (스페이스 블랙)",
    category: "IT/업무장비",
    code: "HYD-IT-04",
    location: "3F VIP 자스민 라운지 데스크",
    status: "LOANED",
    borrower_name: "김태호 디렉터",
    borrower_contact: "공간기획실 (010-8921-XXXX)",
    loaned_at: new Date(Date.now() - 3600000 * 26).toISOString(),
    expected_return_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    description: "미디어 파사드 전시 영상 렌더링 및 프리젠테이션용 고성능 랩탑.",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: "hyd-05",
    name: "소니 WH-1000XM5 노이즈 캔슬링 헤드폰",
    category: "음향/오디오",
    code: "HYD-AU-05",
    location: "B2 크리에이티브 그라운드 오피스",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "집중 업무 및 영상 편집 모니터링용 프리미엄 헤드폰.",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "hyd-06",
    name: "DJI Osmo Pocket 3 크리에이터 콤보",
    category: "카메라/영상",
    code: "HYD-CAM-06",
    location: "B1 테이스티 서울 미디어룸",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "4K 120fps 핸드헬드 짐벌 카메라. 인스타그램 릴스 및 매장 숏폼 제작용.",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: "hyd-07",
    name: "킨들 스크라이브 (Kindle Scribe 64GB + 프리미엄 펜)",
    category: "IT/업무장비",
    code: "HYD-IT-07",
    location: "5F 그린 돔 휴게서재",
    status: "AVAILABLE",
    borrower_name: null,
    borrower_contact: null,
    loaned_at: null,
    expected_return_date: null,
    description: "디지털 필기 및 도서 리딩용 대화면 e-ink 태블릿.",
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_LOGS: RentalLog[] = [
  {
    id: "log-01",
    item_id: "hyd-02",
    item_name: "라이카 SOFORT 2 하이브리드 즉석 카메라",
    action: "BORROW",
    user_name: "이지은 매니저",
    note: "사운즈 포레스트 팝업 스토어 스케치 촬영",
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "log-02",
    item_id: "hyd-04",
    item_name: "맥북 프로 16형 M3 Max (스페이스 블랙)",
    action: "BORROW",
    user_name: "김태호 디렉터",
    note: "공간기획실 미디어 파사드 시연 프리젠테이션",
    timestamp: new Date(Date.now() - 3600000 * 26).toISOString(),
  },
  {
    id: "log-03",
    item_id: "hyd-05",
    item_name: "소니 WH-1000XM5 노이즈 캔슬링 헤드폰",
    action: "RETURN",
    user_name: "박서준 파트장",
    note: "음원 믹싱 작업 완료 후 반납",
    timestamp: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
];
